name: publish

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Set up Python 3.7
      uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
      with:
        python-version: 3.7
    - name: Install dependencies
      run:  |
        pip install --upgrade pip
        pip install --upgrade poetry
    - name: Publish with Poetry
      run: |
        poetry config repositories.pypi "https://pypi.org/legacy/"
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
