name: publish

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Set up Python 3.7
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: 3.7
    - name: Install dependencies
      run:  |
        pip install --upgrade pip
        pip install --upgrade poetry
    - name: Publish with Poetry
      run: |
        poetry config repositories.pypi "https://pypi.org/legacy/"
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
